---
latitude: 45.43498
longitude: 12.33917
map_zoom: 12
name: Relais Piazza San Marco
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: San Marco, 312, Calle San Basso
  street2: ''
  state: ''
  city: Venice
  country: 
  zip_code: '30124'
_hotel_id: REL083
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt/.
